services:
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network
    restart: unless-stopped

  bot:
    build: .
    env_file:
      - .env
    environment:
      - TGBOT_TOKEN=${TGBOT_TOKEN}
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bot_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge
